### ISSUE TITLE
.gitmodules references dead repos

### ISSUE THREAD

**Issue by RagdollClash** [yuzu-mirror/yuzu-mirror.github.io#2]
`https://github.com/yuzu-emu/shared-bulma-theme.git` isn't archived in this org, but there is one on [yuzu-emu-mirror](https://github.com/yuzu-emu-mirror/shared-bulma-theme)
`https://github.com/yuzu-emu/shared-hugo-scripts.git` should direct to [the mirror in this org](https://github.com/yuzu-mirror/shared-hugo-scripts).

I'd imagine after these are fixed, the website will build and [yuzu-mirror.github.io](https://yuzu-mirror.github.io/) will actually show the website.

**Comment by ascpixi** [comment]
Thanks for the heads up! The website fork was more of an afterthought, so I didn't really go through and verify any dependencies, haha ^^'>

Will get to this ASAP!

**Comment by ascpixi** [comment]
The dead repositories have been replaced with mirrored ones, but Jekyll reports a [syntax error](https://github.com/yuzu-mirror/yuzu-mirror.github.io/actions/runs/8171944645/job/22341252606#step:4:1434).
